apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://app.getambassador.io
    chart: telepresence
    targetRevision: 2.20.2
    helm:
      releaseName: traffic-manager
      valueFiles:
      - $values/telepresence/helm-values.yaml
  - repoURL: https://github.com/K3S-HOME/platform.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: 'true'
  revisionHistoryLimit: 10
